### ISSUE TITLE
Multipleviews

### ISSUE THREAD

**Issue by kozmabalazs** [DevAhamed/MultiViewAdapter#11]
Hi @DevAhamed,

I was reading the Multiple Data Sets section on the wiki and I wonder if it is possible to add a header view for each data set?

Also in this example I see that there are two separate list. How can we do if we have one list with different kind of views? (Ex.: a newsfeed where one item is a photo item, one a simple text item and they have different layouts)

Thank you.

**Comment by DevAhamed** [comment]
Yes, you can add headers to every list. Here is the [sample link](https://github.com/DevAhamed/MultiViewAdapter/blob/master/sample/src/main/java/com/ahamed/sample/complex/ComplexListAdapter.java#L59)

For the same list, you can have two different binders. ie., PhotoBinder and TextBinder. Kindly refer this [example for that](https://github.com/DevAhamed/MultiViewAdapter/blob/master/sample/src/main/java/com/ahamed/sample/grid/GridAdapterActivity.java#L50)

**Comment by DevAhamed** [comment]
Feel free to re-open if you are still facing the issue.

**Comment by denimwho** [comment]
How to remove header of that data set when the data is empty?

**Comment by DevAhamed** [comment]
For now, you can call ```removeItem()``` on your [DataItemManager](https://github.com/DevAhamed/MultiViewAdapter/blob/f03fd70dcd43c69bf599816bce532c09787a2fa7/multi-view-adapter/src/main/java/com/ahamed/multiviewadapter/DataItemManager.java#L52) object to remove the header once set.
