### ISSUE TITLE
 I would like to make a suggestion

### ISSUE THREAD

**Issue by ghost** [DevAhamed/MultiViewAdapter#17]
# 1.
  /**
   * Denotes that the item is lies in the middle of the grid
   */
  int POSITION_RIGHT = 4;

  /**
   * Denotes that the item is lies in the right edge of the grid
   */
  int POSITION_BOTTOM = 8;

  /**
   * Denotes that the item is lies in the bottom edge of the grid
   */
  int POSITION_MIDDLE = 0;

why the POSITION_RIGHT ‘s note is rigth ?
this is a accident mistake or this have other meaning？

# 2.
Can you provide a demo about in a RecyclerView with Grid hava different item and different SpanCount ?
I have  read ComplexListActivity ，but This is not what I want。
[https://github.com/DevAhamed/MultiViewAdapter/wiki/Grid-Adapter](url) about specific demo！

Best blessing！
thank you very much！

**Comment by DevAhamed** [comment]
Fixed the documentation issue
