### ISSUE TITLE
any ideas to implement both Single and Multiple mode selection?

### ISSUE THREAD

**Issue by mochadwi** [DevAhamed/MultiViewAdapter#29]
In my case:
1. RadioButtonBinder with MODE_SINGLE_OR_NONE
2. CheckBoxBinder with MODE_MULTIPLE

Is it possible by default?

**Comment by mochadwi** [comment]
http://imgur.com/a/Es13q

**Comment by DevAhamed** [comment]
I know this is a very old issue. Just wanted give an heads up - This feature is now supported from 2.x versions. If you would like to check this feature download the sample app - https://play.google.com/apps/testing/dev.ahamed.mva.sample
