### ISSUE TITLE
Grid Layoutmanger spacing.

### ISSUE THREAD

**Issue by karthiktag** [DevAhamed/MultiViewAdapter#32]
I have to increase gap of grid view items nearly 23dp. But I'm not getting that much spacing in between. Could you please suggest me on this?
My span count is 2:
Actual Result:
Grid1  Grid2
Grid3  Grid4

Excepted Result:
Grid1      Grid2
Grid3      Grid4

**Comment by DevAhamed** [comment]
Sorry for my late response. If you can send some screenshot/images it would be helpful to understand your requirement
