### ISSUE TITLE
Expanding non-child groups

### ISSUE THREAD

**Issue by reuvenlevitsky** [DevAhamed/MultiViewAdapter#45]
Is it possible to expand groups that are not children?
For example, I have a header that says "expand all", when clicking this header I want to expand three different groups bellow this header. 
As far as I can see I can only expand from the ViewHolder itself and that's not enough for this requirement I think.

**Comment by DevAhamed** [comment]
Thanks for the feature request :)

> As far as I can see I can only expand from the ViewHolder itself and that's not enough for this requirement I think

Yes, it is not possible with the current version. I am working on the next big update which will enable this feature for you. Stay tuned :)

**Comment by DevAhamed** [comment]
Added in v2.0.0. Please take a look at docs for implementation.

Documentation - https://devahamed.github.io/MultiViewAdapter
Exact JavaDoc method - https://devahamed.github.io/MultiViewAdapter/javadocs/mva2/adapter/Section.html#hideSection--

**Comment by DevAhamed** [comment]
Closing it for now. Please re-open this issue if the feature is not working as expected.

**Comment by reuvenlevitsky** [comment]
Thanks! I will have a look. Amazing library by the way, very simple to use and works great!
