### ISSUE TITLE
AndroidX Support

### ISSUE THREAD

**Issue by DevAhamed** [DevAhamed/MultiViewAdapter#51]
Since AndroidX packages are now out of beta, its time to add support for new packages. Since this requires a major refactor, my current plan is to release it with v2 refactor.

**Comment by premacck** [comment]
Any updates on this sir?

I have migrated my project to androidX and after that I cannot access fields of holder class (like "itemView")
How can I fix those issues for now?
I have used the following lines in my gradle.properties
android.useAndroidX=true
android.enableJetifier=true

**Comment by vkotovv** [comment]
@premacck It was implemented in 3.0.0 alpha version, see #71
