### ISSUE TITLE
Removing DataItemBinders from Adapter

### ISSUE THREAD

**Issue by premacck** [DevAhamed/MultiViewAdapter#55]
This library was very useful to me. Thank a lot!
Just wanted to know is there any way to remove a registered binder from recyclerAdapter dynamically?

**Comment by DevAhamed** [comment]
Thanks for your kind words!!

Right now there is no way to unregister a binder. But it makes lot of sense to add one. I will add it in the next release. Stay tuned!!

**Comment by premacck** [comment]
Alright! Happy to help

**Comment by premacck** [comment]
But For now, is there any alternative to achieving that?
I was thinking of setting a new adapter instance every time I need to remove a registered binder.

**Comment by premacck** [comment]
Leaving a dot for the help.

**Comment by DevAhamed** [comment]
@premacck Sadly there is no workaround for now except creating new adapter

**Comment by premacck** [comment]
Hey @DevAhamed , Just wanted to follow up whether there is any progress on this issue?

**Comment by DevAhamed** [comment]
Added in v2.0.0-alpha01. Closed by 9a91d77
