### ISSUE TITLE
Expandable groups

### ISSUE THREAD

**Issue by Luis-Barba** [DevAhamed/MultiViewAdapter#60]
Hi! first of all, awesome library!!

I found an issue with the expand collapse feature. While items expand and collapse correctly, groups can't collapse again, except if I click on another group(in EXPANDABLE_MODE_SINGLE). When i call the method isItemExpanded() after toggleGroupExpansion() it returns allways false.

This is a clone of your proyect:

![multiviewadapter](https://user-images.githubusercontent.com/39769758/50441746-69b8a480-08fc-11e9-97ef-de1ce58dfab9.gif)

**Comment by DevAhamed** [comment]
Hi,

Thanks for reporting this issue. I have refactored and updated the sample app. You can download it from here - https://play.google.com/store/apps/details?id=dev.ahamed.mva.sample

You can check the demo and let me know if the issue is still there in the v2.
