### ISSUE TITLE
Is it possible to use different layout managers with multiview adapter?

### ISSUE THREAD

**Issue by Subroid** [DevAhamed/MultiViewAdapter#77]
**Please complete the following information:**
 - Android API level: [e.g. 21]
 - Library Version: [e.g. 2.0.0]
 - Recyclerview Version [e.g. 2.0.0]

**Comment by DevAhamed** [comment]
Yes, you can use any layout manager with MultiViewAdapter library.

**Comment by Subroid** [comment]
I mean to ask is it possible to use multiple layout managers for multiple list sections?

**Comment by DevAhamed** [comment]
Which layout managers you want to use?

**Comment by Subroid** [comment]
I want to have multiple list sections in my home screen. It is an ecommerce app so there will be sections like recommended for you, popular etc list in home screen so I want to use sometimes Linear Layout Mangager for some sections and sometimes Grid Layout Mangager for some sections.

**Comment by DevAhamed** [comment]
If thats the case, you can use GridLayoutManager and set different span count to each section. This is showcased in sample app. You can download the sample app from here : https://play.google.com/apps/testing/dev.ahamed.mva.sample

Switch to 'Advanced' in sample app. You can see that there are different sections inside the single adapter with different span count.
